### ISSUE TITLE
Cakephp 3 - Install error

### ISSUE THREAD

**Issue by pogs94** [froala/wysiwyg-cake#1]
Hello guys,  

i use the following command in the main project folder (C:\xampp\htdocs\projectous)
git clone git://github.com/froala/wysiwyg-cake.git Plugin/Froala

After git the plugin, i'm trying to load it, in the bootstrap.php.

Plugin::load('Froala', ['bootstrap' => true]);

So, i receive the following error ..

![capturar](https://cloud.githubusercontent.com/assets/17783686/25512282/e802b936-2ba2-11e7-94b2-082f681757a9.JPG)

The tutorial is a little bit confusing, can anyone help me please?

Thanks, in advance.

Peter

**Comment by iradustefan** [comment]
Hello, 

Please add to your bootstrap file the following: "Plugin::loadAll();".
This will load the routes for all the plugins.

Let me know if it works.

**Comment by lupoair** [comment]
Should the plugin be cloned into the cakephp plugins instead of Plugin?

**Comment by aungthawdar** [comment]
For me, got the "**Helper class FroalaHelper could not be found.**" after adding this property at the AppController.
public $helpers = array('Froala.Froala');

I've already put the line Plugin::loadAll(); in bootstrap.php too.

**Comment by KoBa4** [comment]
1. composer require froala/wysiwyg-cake
2. bootstrap.php => Plugin::load('Froala');
3. src/View/AppView.php => $this->loadHelper('Froala.Froala');

**Comment by yarkm13** [comment]
@KoBa4 
2. `bin/cake plugin load Froala`
3. can be a `public $helpers = array('Froala.Froala');` in controller, if you need to include only for particular controller
